# Generated by Django 4.2.27 on 2026-01-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "route_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("short_name", models.CharField(max_length=100)),
                ("long_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "stop_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="api.route",
                    ),
                ),
            ],
        ),
    ]
