# Generated by Django 4.2.27 on 2026-01-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.route",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("critical", "Critical"),
                ],
                default="info",
                max_length=10,
            ),
        ),
    ]
