# Generated by Django 4.2.27 on 2026-02-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alert_active_alert_route_alert_severity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stop",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="stop",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
