# Generated by Django 4.2.27 on 2026-01-21 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoptime",
            name="arrival_time",
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
